# Generated by Django 2.0.2 on 2018-03-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
