# Generated by Django 2.0.2 on 2018-03-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0002_auto_20180327_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('metodo_de_pago', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo')], max_length=25)),
            ],
        ),
    ]
