# Generated by Django 2.0.2 on 2018-03-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0003_articulos_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='descripcion',
            field=models.CharField(default='no_nombre', max_length=50),
        ),
    ]
