# Generated by Django 2.0.2 on 2018-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0004_ventas_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='hora',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
