# Generated by Django 2.0.2 on 2018-04-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0005_auto_20180328_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
