# Generated by Django 2.0.2 on 2018-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0006_auto_20180402_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='id',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
