# Generated by Django 2.0.2 on 2018-04-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0009_auto_20180414_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='notas',
        ),
    ]
