# Generated by Django 2.0.2 on 2018-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0010_remove_ventas_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='realizada_por',
            field=models.CharField(default='Otro Tecnico', max_length=25, null=True),
        ),
    ]
