# Generated by Django 2.0.2 on 2018-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0011_auto_20180414_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Tecnico', 'Tecnico')], default='Tecnico', max_length=25),
        ),
    ]
