# Generated by Django 2.0.2 on 2018-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0012_administrador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
