# Generated by Django 2.0.2 on 2018-04-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0015_auto_20180414_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='precio1',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='precio1_currency',
        ),
    ]
