# Generated by Django 2.0.2 on 2018-04-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0016_auto_20180414_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentivosDiarios',
            fields=[
                ('dia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bono_puntualidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
