# Generated by Django 2.0.2 on 2018-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0017_incentivosdiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='objetivo_venta',
            field=models.IntegerField(default=0),
        ),
    ]
