# Generated by Django 2.0.2 on 2018-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0018_articulos_objetivo_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('hora_entrada', models.TimeField()),
                ('cantidad_incentivo', models.IntegerField()),
            ],
        ),
    ]
