# Generated by Django 2.0.2 on 2018-05-16 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0019_horasesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasesion',
            name='hora_sesion',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
