# Generated by Django 2.0.2 on 2018-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0020_horasesion_hora_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('fecha_ultimo_pago', models.DateField(auto_now_add=True)),
                ('cantidad_pago', models.IntegerField()),
            ],
        ),
    ]
