# Generated by Django 2.0.2 on 2018-05-16 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0021_pagoempleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='dias_laborales',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
