# Generated by Django 2.0.2 on 2018-05-16 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstDjangoApp', '0022_administrador_dias_laborales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoempleados',
            old_name='fecha_ultimo_pago',
            new_name='fecha_pago',
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_ultimo_pago',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
